#! /bin/bash

# Uncomment this for debugging.
#ECHO=echo

prog_dir=$(dirname $0)
data=$prog_dir/../raspberry-pi-dashboard/vagrant_home/chromereq.rb
install_dir="$1"
$ECHO mkdir -v -p $install_dir

$ECHO cp -vr $data $install_dir


